### ISSUE TITLE
How to build and run this?

### ISSUE THREAD

**Issue by yadvr** [miguelangelo78/munix#1]

**Comment by miguelangelo78** [comment]
Although the project was not specifically prepared for building through a simple execution of make, it can be built by running the makefiles inside the folder 'munix_toolchain'. This is because at the start of the development my IDE of choice was Eclipse and it was the IDE's responsibility to generate the makefiles.

**Comment by yadvr** [comment]
Cool, thanks for replying I'll see if I can build something
